### ISSUE TITLE
Is this now legacy in light of Meteor 1.3?

### ISSUE THREAD

**Issue by zeroasterisk** [zhongqf/meteoredux#3]

**Comment by zhongqf** [comment]
Yes, it aimed for Meteor 1.2
I have no time to test it with new meteor 1.3
So if you want to connect redux with meteor 1.3 maybe you need to check something else. 
Sorry

**Comment by samylaumonier** [comment]
I created a package that allows you to use React and Redux with Meteor 1.4 in a clean way.

Thanks to two Redux middlewares, you can subscribe with Redux actions and sync your Redux store with the data from Mongo or from any reactive data source.

The package: https://github.com/samybob1/meteor-redux-middlewares/
The live demo: https://meteor-redux-middlewares-demo.herokuapp.com/
The demo sources on GitHub: https://github.com/samybob1/meteor-redux-middlewares-demo/
